version: "2.0"

services:

  postgres:
    image: postgres
    environment:
        - POSTGRES_USER=ojs
        - POSTGRES_PASSWORD=ojs
    ports:
        - "5432:5432"

  redis:
    image: redis:3.2.4-alpine

  memcached:
     image: memcached:1.4.32-alpine

  elasticsearch:
    image: elasticsearch:1.7.5
    command: -E network.host=0.0.0.0
    environment:    
         ES_JAVA_OPTS: "-Xms1g -Xmx1g"

  nginx:
    build: ./nginx
    image: ojs:nginx
    links:
      - fpm
      - postgres
      - elasticsearch
      - redis
      - memcached
    volumes:
      - ../app/web:/srv/web
    depends_on:
      - fpm
      - postgres
      - redis
      - memcached
      - elasticsearch

  fpm:
    build: ./ojs
    image: ojs:fpm
    env_file: secrets.env
